import {t, type TranslationKey} from '../i18n';

/** Player-facing coaching when Spark is blocked — never internal type codes like "RING B". */
const FAIL_TIP: Record<string, TranslationKey> = {
  rotor: 'fail.time_the_gap',
  slidingGate: 'fail.wait_for_opening',
  splitShutter: 'fail.wait_for_opening',
  reactiveGate: 'fail.wait_for_opening',
  scissorGate: 'fail.wait_for_opening',
  iris: 'fail.slip_through_open',
  shiftingAperture: 'fail.slip_through_open',
  rollingAperture: 'fail.slip_through_open',
  dockingCollar: 'fail.slip_through_open',
  airlockIris: 'fail.slip_through_open',
  pendulum: 'fail.wait_for_swing',
  antennaBoom: 'fail.wait_for_swing',
  movingRing: 'fail.lead_the_ring',
  pulseRing: 'fail.between_pulses',
  orbiter: 'fail.quiet_lane',
  driftingBlocker: 'fail.quiet_lane',
  formation: 'fail.quiet_lane',
  accretionShredder: 'fail.quiet_lane',
  debrisSpiral: 'fail.quiet_lane',
  phaseField: 'fail.true_path',
  falseLightMembrane: 'fail.true_path',
  laserGrid: 'fail.between_beams',
  groundCutLasers: 'fail.between_beams',
  pulsarBeam: 'fail.between_beams',
  pistonField: 'fail.read_the_blocks',
  elevatorBlocks: 'fail.read_the_blocks',
  conveyorGate: 'fail.read_the_blocks',
  clockHands: 'fail.pass_the_sweep',
  speedField: 'fail.ride_the_current',
  shearLane: 'fail.ride_the_current',
  energyField: 'fail.safe_window',
  phaseGate: 'fail.safe_window',
  nullTendril: 'fail.avoid_the_dark',
  nullLash: 'fail.avoid_the_dark',
  theNull: 'fail.avoid_the_dark',
  lagrangeNull: 'fail.avoid_the_dark',
  quietPocket: 'fail.avoid_the_dark',
  teleportPortal: 'fail.verify_the_exit',
  entryExitPortal: 'fail.verify_the_exit',
  teleportChain: 'fail.verify_the_exit',
  teleportingPortal: 'fail.verify_the_exit',
  rotatingGate: 'fail.open_sector',
  billboardFlip: 'fail.clear_face',
  cometCrossing: 'fail.thread_the_lights',
  orbitingMoons: 'fail.thread_the_lights',
  solarSail: 'fail.thread_the_lights',
  magnetopause: 'fail.thread_the_lights',
  corkscrewTunnel: 'fail.follow_open_path',
  sequentialTunnel: 'fail.follow_open_path',
  movingSafeZone: 'fail.follow_open_path',
  networkTunnel: 'fail.follow_open_path',
  transitConduit: 'fail.follow_open_path',
  retrievalScanner: 'fail.safe_window',
  repulsor: 'fail.account_for_push',
};

export function failTip(type: string): string {
  return t(FAIL_TIP[type] ?? 'fail.read_then_commit');
}
