export const ANALYTICS_EVENTS = {
  appOpen: 'app_open',
  onboardingStarted: 'onboarding_started',
  onboardingCompleted: 'onboarding_completed',
  runStarted: 'run_started',
  runEnded: 'run_ended',
  retryStarted: 'retry_started',
  shotStarted: 'shot_started',
  shotSuccess: 'shot_success',
  shotFailed: 'shot_failed',
  obstacleCollision: 'obstacle_collision',
  targetMiss: 'target_miss',
  bullseye: 'bullseye',
  perfect: 'perfect',
  closeCall: 'close_call',
  environmentEntered: 'environment_entered',
  loopCompleted: 'loop_completed',
  newHighScore: 'new_high_score',
  levelUp: 'level_up',
  projectileUnlocked: 'projectile_unlocked',
  projectileSelected: 'projectile_selected',
  continueOffered: 'continue_offered',
  continueSelected: 'continue_selected',
  continueAdStarted: 'continue_ad_started',
  continueAdCompleted: 'continue_ad_completed',
  continueAdFailed: 'continue_ad_failed',
  continueDeclined: 'continue_declined',
  interstitialEligible: 'interstitial_eligible',
  interstitialShown: 'interstitial_shown',
  interstitialFailed: 'interstitial_failed',
  interstitialDismissed: 'interstitial_dismissed',
  purchaseStarted: 'purchase_started',
  purchaseCompleted: 'purchase_completed',
  purchaseFailed: 'purchase_failed',
  purchaseRestored: 'purchase_restored',
  levelStarted: 'level_started',
  levelCompleted: 'level_completed',
  levelFailed: 'level_failed',
  levelReplayed: 'level_replayed',
  campaignStarted: 'campaign_started',
  worldEntered: 'world_entered',
  worldCompleted: 'world_completed',
  campaignCompleted: 'campaign_completed',
  endlessVoyageUnlocked: 'endless_voyage_unlocked',
  shardsEarned: 'shards_earned',
  shardsSpent: 'shards_spent',
  energySpent: 'energy_spent',
  energyEmpty: 'energy_empty',
  rewardedEnergyOffered: 'rewarded_energy_offered',
  rewardedEnergyCompleted: 'rewarded_energy_completed',
  unlimitedEnergyPurchased: 'unlimited_energy_purchased',
  boostSelected: 'boost_selected',
  boostUsed: 'boost_used',
  boostPurchasedShards: 'boost_purchased_shards',
  skinEquipped: 'skin_equipped',
  skinPurchasedShards: 'skin_purchased_shards',
} as const;

export type AnalyticsEventName = (typeof ANALYTICS_EVENTS)[keyof typeof ANALYTICS_EVENTS];

export type AnalyticsProperties = Record<string, string | number | boolean | null | undefined>;
