export const ANALYTICS_EVENTS = {
  appOpen: 'app_open',
  onboardingStarted: 'onboarding_started',
  onboardingCompleted: 'onboarding_completed',
  runStarted: 'run_started',
  runEnded: 'run_ended',
  retryStarted: 'retry_started',
  shotStarted: 'shot_started',
  shotSuccess: 'shot_success',
  shotFailed: 'shot_failed',
  obstacleCollision: 'obstacle_collision',
  targetMiss: 'target_miss',
  bullseye: 'bullseye',
  perfect: 'perfect',
  closeCall: 'close_call',
  environmentEntered: 'environment_entered',
  loopCompleted: 'loop_completed',
  newHighScore: 'new_high_score',
  levelUp: 'level_up',
  projectileUnlocked: 'projectile_unlocked',
  projectileSelected: 'projectile_selected',
  continueOffered: 'continue_offered',
  continueSelected: 'continue_selected',
  continueAdStarted: 'continue_ad_started',
  continueAdCompleted: 'continue_ad_completed',
  continueAdFailed: 'continue_ad_failed',
  continueDeclined: 'continue_declined',
  interstitialEligible: 'interstitial_eligible',
  interstitialShown: 'interstitial_shown',
  interstitialFailed: 'interstitial_failed',
  interstitialDismissed: 'interstitial_dismissed',
  purchaseStarted: 'purchase_started',
  purchaseCompleted: 'purchase_completed',
  purchaseFailed: 'purchase_failed',
  purchaseRestored: 'purchase_restored',
} as const;

export type AnalyticsEventName = (typeof ANALYTICS_EVENTS)[keyof typeof ANALYTICS_EVENTS];

export type AnalyticsProperties = Record<string, string | number | boolean | null | undefined>;
