import type { WorldDefinition } from './types';

export const WORLDS: WorldDefinition[] = [
  {
    id: 'containment',
    index: 1,
    name: 'CONTAINMENT',
    subtitle: 'Underground research facility',
    firstLevel: 1,
    lastLevel: 15,
    environmentId: 'workshop',
    storyBeat: 'SPECIMEN S-01 escapes containment.',
    primaryMechanics: ['rotor', 'laserGrid'],
    homeSignalStrength: 'faint',
    distanceFromEarth: '0 KM FROM EARTH',
    finaleName: 'LOCKDOWN',
    completionSparkId: 'reactor',
    stub: false,
  },
  {
    id: 'city',
    index: 2,
    name: 'THE CITY',
    subtitle: 'Streets and rooftops above the facility',
    firstLevel: 16,
    lastLevel: 30,
    environmentId: 'rooftop',
    storyBeat: 'Spark races across the city toward the sky.',
    primaryMechanics: ['slidingGate', 'wind'],
    homeSignalStrength: 'faint',
    distanceFromEarth: '12 KM FROM EARTH',
    finaleName: 'CITY LIMITS',
    completionSparkId: 'neon',
    stub: false,
  },
  {
    id: 'sky',
    index: 3,
    name: 'THE SKY',
    subtitle: 'Storm-cut altitudes',
    firstLevel: 31,
    lastLevel: 45,
    environmentId: 'rooftop',
    storyBeat: 'Crosswinds and moving rings.',
    primaryMechanics: ['movingRing', 'crosswind'],
    homeSignalStrength: 'faint',
    distanceFromEarth: '8 KM ABOVE EARTH',
    finaleName: 'THE STORM',
    completionSparkId: 'storm',
    stub: false,
  },
  {
    id: 'atmosphere',
    index: 4,
    name: 'UPPER ATMOSPHERE',
    subtitle: 'Thin air, iris locks',
    firstLevel: 46,
    lastLevel: 60,
    environmentId: 'space',
    storyBeat: 'Gravity softens. Escape velocity awaits.',
    primaryMechanics: ['iris', 'gravityReduction'],
    homeSignalStrength: 'detectable',
    distanceFromEarth: '100 KM FROM EARTH',
    finaleName: 'ESCAPE VELOCITY',
    completionSparkId: 'aurora',
    stub: false,
  },
  {
    id: 'orbit',
    index: 5,
    name: 'ORBIT',
    subtitle: 'Debris and silence',
    firstLevel: 61,
    lastLevel: 75,
    environmentId: 'space',
    storyBeat: 'Low gravity graveyard.',
    primaryMechanics: ['pendulum', 'lowGravity'],
    homeSignalStrength: 'detectable',
    distanceFromEarth: '400 KM FROM EARTH',
    finaleName: 'ORBITAL GRAVEYARD',
    completionSparkId: 'solar',
    stub: false,
  },
  {
    id: 'moon',
    index: 6,
    name: 'THE MOON',
    subtitle: 'Far side signal',
    firstLevel: 76,
    lastLevel: 90,
    environmentId: 'space',
    storyBeat: 'Gravity wells bend every throw.',
    primaryMechanics: ['orbiter', 'gravityWells'],
    homeSignalStrength: 'detectable',
    distanceFromEarth: '384,000 KM FROM EARTH',
    finaleName: 'FAR SIDE',
    completionSparkId: 'lunar',
    stub: false,
  },
  {
    id: 'asteroid',
    index: 7,
    name: 'ASTEROID BELT',
    subtitle: 'Many routes, one timing',
    firstLevel: 91,
    lastLevel: 105,
    environmentId: 'space',
    storyBeat: 'Drifting blockers. Choose a lane.',
    primaryMechanics: ['driftingBlockers', 'multipleRoutes'],
    homeSignalStrength: 'strong',
    distanceFromEarth: '2.7 AU FROM EARTH',
    finaleName: 'COLLISION COURSE',
    completionSparkId: 'meteor',
    stub: false,
  },
  {
    id: 'nebula',
    index: 8,
    name: 'THE NEBULA',
    subtitle: 'False lights',
    firstLevel: 106,
    lastLevel: 120,
    environmentId: 'space',
    storyBeat: 'Phase windows and energy fields.',
    primaryMechanics: ['energyField', 'phaseWindows'],
    homeSignalStrength: 'strong',
    distanceFromEarth: 'LIGHT YEARS FROM EARTH',
    finaleName: 'FALSE HOME',
    completionSparkId: 'nebula',
    stub: false,
  },
  {
    id: 'network',
    index: 9,
    name: 'THE ANCIENT NETWORK',
    subtitle: 'Synchronized apertures',
    firstLevel: 121,
    lastLevel: 135,
    environmentId: 'space',
    storyBeat: 'The Key reveals where home truly is.',
    primaryMechanics: ['shiftingAperture', 'synchronized'],
    homeSignalStrength: 'located',
    distanceFromEarth: 'BEYOND THE MAP',
    finaleName: 'THE KEY',
    completionSparkId: 'ancient',
    stub: false,
  },
  {
    id: 'homeward',
    index: 10,
    name: 'HOMEWARD',
    subtitle: 'Everything learned',
    firstLevel: 136,
    lastLevel: 150,
    environmentId: 'space',
    storyBeat: 'No new families — only the way home.',
    primaryMechanics: ['combined'],
    homeSignalStrength: 'home',
    distanceFromEarth: 'HOME',
    finaleName: 'HOME',
    completionSparkId: 'origin',
    stub: false,
  },
];

export const TOTAL_CORE_LEVELS = 150;

export function worldById(id: string): WorldDefinition | undefined {
  return WORLDS.find((world) => world.id === id);
}

export function worldForLevel(levelNumber: number): WorldDefinition | undefined {
  return WORLDS.find((world) => levelNumber >= world.firstLevel && levelNumber <= world.lastLevel);
}

export function journeyDestinationLabel(unlockedWorldIds: string[], campaignCompleted: boolean): string {
  if (campaignCompleted || unlockedWorldIds.includes('homeward')) {
    return 'HOME';
  }
  if (unlockedWorldIds.includes('network')) {
    return 'HOME';
  }
  return 'UNKNOWN';
}
